### ISSUE TITLE
Default make-method-lambda doesn't add implicit blocks around the method body.

### ISSUE THREAD

**Issue by marcoheisig** [pcostanza/closer-mop#15]
The following code signals "Error: return for unknown block: foo".

```lisp
(in-package #:closer-common-lisp)

(defclass gf (standard-generic-function)
  ()
  (:metaclass funcallable-standard-class))

(defgeneric foo (x)
  (:generic-function-class gf))

;; This method on MAKE-METHOD-LAMBDA is necessary to suppress the default
;; expansion DEFMETHOD and use the expander from CLOSER-MOP instead.
(defmethod make-method-lambda :before ((gf gf) method lambda env)
  (declare (ignore gf method lambda env)))

(defmethod foo ((x integer))
  (return-from foo x))
```
It seems closer-mop's expansion of make-method-lambda doesn't add the necessary implicit blocks around the method function body.

**Comment by pcostanza** [comment]
Thanks a lot for reporting this. I will look into this, but cannot promise that I can react fast at the moment. (Maybe, maybe not.) As a temporary workaround, can you create the necessary block manually in the user code until this is fixed?

**Comment by marcoheisig** [comment]
I can even offer to make a pull request myself.  That shouldn't be too much work...

**Comment by marcoheisig** [comment]
OK, I just submitted a pull request.

**Comment by pcostanza** [comment]
Quick note: Sorry for the delay in working on this. There are several reasons: The COVID-19 situation caused some delay (nothing to worry about, no serious issues). Also, since I moved my system to macOS Mojave, I can't run 32-bit apps anymore, which means I can't easily test Allegro Common Lisp and CMUCL anymore. Franz haven't responded to a request for a 64-bit "express" or evaluation version. I will now try to set up a 32-bit Linux system to be able to test ACL and CMUCL. And then ECL got a new version, which seems to have introduced one or two new CLOS MOP bugs and make ContextL and AspectL fail. And I haven't tested the new ABCL yet... So lots of work.

I hope your issue isn't urgent. If so, please let me know, so I can try to prioritize it.

**Comment by marcoheisig** [comment]
Thanks for keeping me up to date.  The issue isn't urgent - I fixed it in my local copy of closer-mop and that is enough to continue development.  But I'd love to see a fix over the next year or so.

Stay healthy!
