### ISSUE TITLE
Redefined standard-generic-function.

### ISSUE THREAD

**Issue by SweetHat** [pcostanza/closer-mop#5]
Hello.
I use Clozure Common Lisp 1.11 and I have found that
method COMPUTE-APPLICABLE-METHODS-USING-CLASSES is defined for (**CLOSER-MOP**:STANDARD-GENERIC-FUNCTION T), so, for example, calling it with #'PRINT-OBJECT (which is **COMMON-LISP**:STANDARD-GENERIC-FUNCTION) results in 'Error: There is no applicable method...'

**Comment by pcostanza** [comment]
closer-mop:standard-generic-function and common-lisp:standard-generic-function are not the same. Since #'print-object is a common-lisp:standard-generic-function, closer-mop:compute-applicable-methods-using-classes doesn't work on #'print-object. You should use ccl:compute-applicable-methods-using-classes instead (or just compute-applicable-methods).

Here is the rationale: c-a-m-u-c and c-a-m serve two purposes. One is to inspect which methods would be computed for a particular set of arguments, which is primarily interesting for debugging. The other is to define methods for c-a-m-u-c and c-a-m to change which methods will be computed for one's own generic function metaobject class. Debugging is a temporary activity for which you don't need fully portable abstractions. Influencing method dispatch, however, has long-lasting uses in libraries and applications, so portability is more important here.

Ideally, a portability library like Closer to MOP should serve both purposes, but this is unfortunately not possible due to restrictions in the CLOS MOP. Therefore I had to prioritize which purpose to focus on, and decided to go for the second one.
