### ISSUE TITLE
Reader functions for method-combination class

### ISSUE THREAD

**Issue by Chream** [pcostanza/closer-mop#7]
I found that I had to define some portability reader methods for method-combination objects. Is this something that closer-mop wants to integrate?

```
(defgeneric method-combination-type-name (method-combination))
(defgeneric method-combination-options (method-combination))

(defmethod method-combination-type-name ((object method-combination))
  #+sbcl (sb-pcl::method-combination-type-name object)
  #+ccl (ccl::method-combination-name object)
  #+allegro (excl::method-combination-type object)
  #+ecl (mop::method-combination-name object))

(defmethod method-combination-options ((object method-combination))
  #+sbcl (sb-pcl::method-combination-options object)
  #+ccl (ccl::method-combination-options object)
  #+allegro (excl::method-combination-options object)
  #+ecl (mop::method-combination-options object))
```

**Comment by pcostanza** [comment]
The goal of Closer to MOP is to make different CLOS MOP implementations adhere better to the AMOP specification. Since method combination types are not specified in the AMOP, it's unlikely that I will add them. It's probably more appropriate to get features like this included in cl-mop, mop-utils, moptilities, or similar libraries.
